export const MESSAGE = {
  HIDE: "HIDE_MESSAGE",
  SHOW: "SHOW_MESSAGE",
}

export const REGISTER_USER = {
  REQUEST: "REGISTER_USER_REQUEST",
  SUCCESS: "REGISTER_USER_SUCCESS",
  ERROR: "REGISTER_USER_ERROR",
}

export const LOGIN_USER = {
  REQUEST: "LOGIN_USER_REQUEST",
  SUCCESS: "LOGIN_USER_SUCCESS",
  ERROR: "LOGIN_USER_ERROR",
}

export const LOGOUT_USER = "LOGOUT_USER"

export const AUTHENTICATE_USER = {
  REQUEST: "AUTHENTICATE_USER_REQUEST",
  SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  ERROR: "AUTHENTICATE_USER_ERROR",
}

export const CONFIGURATION_DATABASE_SYNC = {
  REQUEST: "CONFIGURATION_DATABASE_SYNC_REQUEST",
  SUCCESS: "CONFIGURATION_DATABASE_SYNC_SUCCESS",
  ERROR: "CONFIGURATION_DATABASE_SYNC_ERROR",
}

export const GENERATE_PDF_FILES = {
  REQUEST: "GENERATE_PDF_FILES_REQUEST",
  SUCCESS: "GENERATE_PDF_FILES_SUCCESS",
  ERROR: "GENERATE_PDF_FILES_ERROR",
}

export const GET_PDF_FILES = {
  REQUEST: "GET_PDF_FILES_REQUEST",
  SUCCESS: "GET_PDF_FILES_SUCCESS",
  ERROR: "GET_PDF_FILES_ERROR",
}

export const SEND_PDF_FILES = {
  REQUEST: "SEND_PDF_FILES_REQUEST",
  SUCCESS: "SEND_PDF_FILES_SUCCESS",
  ERROR: "SEND_PDF_FILES_ERROR",
}

export const SET_NOT_SENT_PDF_FILES = {
  REQUEST: "SET_NOT_SENT_PDF_FILES_REQUEST",
  SUCCESS: "SET_NOT_SENT_PDF_FILES_SUCCESS",
  ERROR: "SET_NOT_SENT_PDF_FILES_ERROR",
}

export const GET_NOT_SENT_PDF_FILES = {
  REQUEST: "GET_NOT_SENT_PDF_FILES_REQUEST",
  SUCCESS: "GET_NOT_SENT_PDF_FILES_SUCCESS",
  ERROR: "GET_NOT_SENT_PDF_FILES_ERROR",
}
