export const SESSION_LOGIN = "SESSION_LOGIN"
export const SESSION_LOGOUT = "SESSION_LOGOUT"

export const CONFIGURATION_DATABASE_SYNC = {
  REQUEST: "CONFIGURATION_DATABASE_SYNC_REQUEST",
  SUCCESS: "CONFIGURATION_DATABASE_SYNC_SUCCESS",
  ERROR: "CONFIGURATION_DATABASE_SYNC_ERROR",
}
